services:
  - type: web
    name: codealpha-object-tracking
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: YOLO_CONFIG_DIR
        value: /tmp/Ultralytics
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
